changelog:
  categories:
    - title: Breaking changes 🛠
      labels:
        - breaking-change
    - title: Non-breaking changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies
